on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      uses: actions/checkout@master
#    - name: Build
#      run: docker build -t IU-IPOD-F20/refactoring-project-SimonWT:${GITHUB_REF##*/} .