on: [push]

jobs:
  check_app:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      uses: IU-IPOD-F20/refactoring-project-SimonWT@master
#    - name: lgeiger/black-action@master
#      args: . --check