on: [push]

jobs:
  check_app:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      uses: IU-IPOD-F20/refactoring-project-SimonWT@master
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable